name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout main branch"
        uses: actions/checkout@v2
      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: "Install Yarn"
        run: npm install -g yarn
      - name: "Install dependencies"
        run: yarn install --frozen-lockfile --prod
      - name: "Publish to NPM"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
